run_tool_server:
	uv run uvicorn giga_agent.tool_server.tool_server:app --reload --port 8811

run_graph:
	uv run langgraph dev --no-browser

run_giga_agent_api:
	uv run uvicorn giga_agent.tasks_app:app --reload --port 8822